services:
  llm-env:
    build:
      context: .
    container_name: llm-dev-container
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    entrypoint: ["/workspace/bootstrap.sh"]
    tty: true
    stdin_open: true
